config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/user/sign_out' => 'devise/sessions#destroy'
  end
 
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users
  resources :group, only: [:index, :new, :create] do
    resources :cost, only: [:index, :new, :create]
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :cost_groups
  has_many :costs, through: :cost_groups
  validates :name, presence: true
  validates :user_id, presence: true
  validates :icon, presence: true
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  load_and_authorize_resource
  def index
    @groups = Group.where(user: current_user)
    @group_costs = total_costs
  end

  def new; end

  def create
    @group.user = current_user
    if @group.save
      redirect_to root_path, notice: 'Succesfully created new group'
    else
      flash[:alert] = 'Error creating new group'
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end

  def total_costs
    return {} if current_user.nil?

    group_costs = {}
    @groups.each do |group|
      amount = 0
      group.costs.each do |cost|
        amount += cost.amount
      end
      group_costs[group.id] = amount
    end
    group_costs
  end
end

app/helpers/group_helper.rb
module GroupHelper
end

app/views/group/index.html.erb
<%= render "shared/nav_bar", name: 'Categories', display: 'd-none',  route: root_path %>
<section>
  <% @groups.each do |group|%>
    <%= link_to group_cost_index_path(group.id), :action => 'go' do %>
      <div class="container d-flex border my-3 align-items-center justify-content-around">
        <img src='<%= group.icon %>' width="100" height="80" alt="Icon">
        <p><%= group.name %></p>
        <p class="fw-bold"><%= @group_costs[group.id] %></p>
      </div>
    <% end %>
  <% end %>
</section>
<div class="green-color d-flex justify-content-center">
  <%= link_to "Add Category", new_group_path ,class:"button border text-white py-2 px-5 m-2" %> 
</div>

app/views/group/new.html.erb
<%= render "shared/nav_bar", name: 'New Category', display: '', route: root_path %>

<%= form_with model: @group, url: group_index_path do |form| %>
  <%= render "shared/form_errors", form: form %>
  <div class="mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control", placeholder: "name", :required => true  %>
  </div>
  <div class="mb-3">
    <%= form.label :icon %>
    <%= form.text_field :icon, class:"form-control", placeholder: "icon", :required => true  %>
  </div>
  <div class="mb-3">
    <div class="green-color d-flex justify-content-center">
      <%= form.submit  "Add Category", class:"btn border text-white py-2 px-5 m-2", data: { turbo: false } %>
    </div>
  </div>
<% end %>